### ISSUE TITLE
Promote Logging to Stable

### ISSUE THREAD

**Issue by mfine** [swift-nav/libsbp#167]
To reach SBP version 1.0, we should promote the logging to stable. Namely, some logging that support debug, info, error, etc. Should deprecate MSG_PRINT and remove MSG_DEBUG_VAR.

/cc @mookerji @fnoble

**Comment by mfine** [comment]
What do we think about deprecating MSG_PRINT (which uses that beastly string with newline terminator) and move to MSG_LOG which includes a level?

**Comment by mookerji** [comment]
+1 so hard

**Comment by denniszollo** [comment]
Would this be treating the first CHAR in the string as the log level and just replacing the macro in the firmware, or something more complete?

Also, we should definitely also add the console filter for log level if we do this.

**Comment by mfine** [comment]
The macro is in libswfitnav, and it's putting a string up front. How about we move from printf to a log function which then takes a level (byte, short, or int) and encodes a message with a string and a int. Unfortunately, this would be pretty piksi_firmware oriented - not sure how to incoporate that with libswiftnav. @fnoble thoughts?

**Comment by denniszollo** [comment]
How about we use the preprocessor with a define ARM or something through the makefile? (makefile should now when it's compiling libswiftnav for a piksi target, right?)

**Comment by mfine** [comment]
We could do something like that if we thought it was ok and not too obscure - point `log_warn(str` etc, at `log(WARN, str` on piksi builds, and the string prepending elsewhere.

**Comment by mfine** [comment]
@mookerji For backwards compatibility, I'm thinking of adding a newlinestring to the YAML. Just for these print messages.

**Comment by mookerji** [comment]
I'm in favor of having something like 

```yaml
 - MSG_LOG:
    id: 0x0203
    public: True
    short_desc: Bar
    desc: Foo
    fields:
          - level:
              type: u8
              desc: Logging level flag
              fields: 
                - 4-7:
                    desc: Reserved
                - 0-3:
                    desc: Logging level
                    values:
                        - 0: INFO
                        - 1: DEBUG
                        - 2: TRACE
          - text:
              type: string
              desc: Human readable string
```

Also, "newlinestring to the yaml"?
